version: '2'
services:
 web:
  image: "$PARAM"
  ports:
    - "0.0.0.0:80:8080"
  dns:
    - "8.8.8.8"
  links:
    - "db:sarjunkumar24391/mysql_app"

 db:
  image: sarjunkumar24391/mysql_app:4.0
  environment:
   - "MYSQL_ROOT_PASSWORD: petclinic"
   - "MYSQL_USER: root"
   - "MYSQL_PASSWORD: petclinic"
   
  ports:
   - "3306:3306"
  dns:
   - 9.9.9.9
  volumes:
   - /petclinic/database:/var/lib/mysql
